### ISSUE TITLE
Error while running "npm run dev"

### ISSUE THREAD

**Issue by tanuj83** [tulios/burrow-stats#6]
I see below error while running "npn run dev" 

$ node -v
v7.0.0
npm -v
3.10.8

 Starting child process with 'node bin/server.js'
/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/tanuj/Documents/burrow-stats/node_modules/burrow-stats/server/index.js: Unknown option: base.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
    at Logger.error (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:20)
    at OptionManager.init (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transformFileSync (/Users/tanuj/Documents/burrow-stats/node_modules/babel-core/lib/api/node.js:138:10)
    at compile (/Users/tanuj/Documents/burrow-stats/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/tanuj/Documents/burrow-stats/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tanuj/Documents/burrow-stats/node_modules/babel-register/lib/node.js:154:7)
Program node bin/server.js exited with code 1

**Comment by tulios** [comment]
Thanks, I'll take a look

**Comment by tanuj83** [comment]
I used prod env and it works

**Comment by tulios** [comment]
It should work anyway, I'll keep it open to investigate this
